### ISSUE TITLE
Implement Path searching algorithm

### ISSUE THREAD

**Issue by Blarc** [Blarc/crowd-evacuation#4]
Implement path searching algorithm as described in the article. (similary as ObstacleAvoiding)

**Comment by mb0484** [comment]
One part of path searching algorithm is sum of impact of obstacles, where it would be good if we would already have a system, with which we would be able to simulate other obstacles (e.g. walls). I think it would be better if we would first implement a system for wall visualisation and placement. I opened new issue #6 .
